name: CI/CD GKE
on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

env:
  GKE_CLUSTER: ecommerce-cluster-1
  GKE_ZONE: southamerica-east1-a

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: haungi/ecommerce-admin-frontend
          tag-sha: true
      
      - name: QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.prod
          platforms: linux/amd64,linux/arm64,linux386
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      
      - name: Gke Credentials
        id: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: "$GKE_CLUSTER"
          location: "$GKE_ZONE"
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set deployment image
        run: kubectl set image deployment ecommerce-admin-frontend ecommerce-admin-frontend=haungi/ecommerce-admin-frontend:${{ steps.docker_meta.outputs.tags }}